"""
Reporter Agent — Visualization & Reporting Engine
Aggregates pipeline results into dashboard metrics, charts data, and executive summaries.
"""

from typing import Dict, Any, List, Optional
from collections import Counter
from datetime import datetime
from loguru import logger

from src.agents.base_agent import BaseAgent


class ReporterAgent(BaseAgent):
    """Aggregates pipeline results into metrics and reports."""

    def __init__(self):
        super().__init__("Reporter")

    def _aggregate_metrics(self, incidents: List[Dict], response_plans: List[Dict]) -> Dict:
        """Compute dashboard statistics."""
        total = len(incidents)
        by_risk = Counter(i.get("risk_level", "LOW") for i in incidents)
        by_type = Counter(i.get("attack_type", "Unknown") for i in incidents)
        by_method = Counter(
            i.get("original_anomaly", {}).get("detection_method", "unknown") for i in incidents
        )

        # Top suspicious IPs
        all_ips = [i.get("ip_address", "") for i in incidents if i.get("ip_address")]
        top_ips = Counter(all_ips).most_common(5)

        # Timeline data
        timeline = []
        for inc in incidents:
            ts = inc.get("timestamp", "")
            if ts:
                try:
                    dt = datetime.fromisoformat(ts[:10])
                    timeline.append({"date": dt.strftime("%Y-%m-%d"), "count": 1})
                except Exception:
                    pass

        # Aggregate timeline by date
        date_counts: Dict[str, int] = {}
        for t in timeline:
            date_counts[t["date"]] = date_counts.get(t["date"], 0) + 1
        timeline_agg = [{"date": d, "count": c} for d, c in sorted(date_counts.items())]

        # Response stats
        urgent_count = sum(1 for r in response_plans if r.get("action_priority") == "URGENT")

        avg_confidence = (
            sum(i.get("confidence_breakdown", {}).get("final_confidence", 0.5) for i in incidents) / max(total, 1)
        )

        return {
            "total_threats": total,
            "by_risk_level": dict(by_risk),
            "by_attack_type": dict(by_type),
            "by_detection_method": dict(by_method),
            "top_suspicious_ips": [{"ip": ip, "count": cnt} for ip, cnt in top_ips],
            "timeline": timeline_agg,
            "urgent_responses": urgent_count,
            "avg_confidence": round(avg_confidence, 3),
            "critical_count": by_risk.get("CRITICAL", 0),
            "high_count": by_risk.get("HIGH", 0),
            "medium_count": by_risk.get("MEDIUM", 0),
            "low_count": by_risk.get("LOW", 0),
            "generated_at": datetime.utcnow().isoformat(),
        }

    def _generate_executive_summary(self, metrics: Dict, incidents: List[Dict]) -> str:
        total = metrics["total_threats"]
        critical = metrics["critical_count"]
        high = metrics["high_count"]
        top_ip = metrics["top_suspicious_ips"][0]["ip"] if metrics["top_suspicious_ips"] else "N/A"

        attack_types = metrics["by_attack_type"]
        top_attack = max(attack_types, key=attack_types.get) if attack_types else "Unknown"

        summary = f"""# Cybersecurity Incident Report
**Generated:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}

---

## Executive Summary

During the monitoring period, the system detected **{total} security threats** across the infrastructure.

### Key Findings:
- **{critical} CRITICAL** and **{high} HIGH** severity incidents require immediate attention
- The most prevalent attack pattern was **{top_attack}** ({attack_types.get(top_attack, 0)} incidents)
- Most active threat source: **{top_ip}**
- Average detection confidence: **{metrics['avg_confidence']:.0%}**

### Risk Distribution:
| Risk Level | Count |
|-----------|-------|
| 🔴 CRITICAL | {metrics['critical_count']} |
| 🟠 HIGH | {metrics['high_count']} |
| 🟡 MEDIUM | {metrics['medium_count']} |
| 🟢 LOW | {metrics['low_count']} |

### Detection Methods Used:
{chr(10).join(f"- **{method}**: {count} detections" for method, count in metrics['by_detection_method'].items())}

## Recommendations

1. Immediately investigate all CRITICAL threats and implement suggested response actions
2. Review the {high} HIGH priority incidents within the next hour
3. Consider IP-level blocking for repeat offenders
4. Update detection thresholds based on current false positive feedback

---
*Report generated by the Multi-Agent Cybersecurity System — Reporter Agent*
"""
        return summary

    def process(self, input_data: Any) -> Dict:
        """
        input_data: dict with 'incidents' and 'response_plans' lists
        Returns aggregated metrics and executive summary.
        """
        if isinstance(input_data, dict):
            incidents = input_data.get("incidents", [])
            response_plans = input_data.get("response_plans", [])
        else:
            incidents = input_data if isinstance(input_data, list) else []
            response_plans = []

        metrics = self._aggregate_metrics(incidents, response_plans)
        summary = self._generate_executive_summary(metrics, incidents)

        result = {
            "metrics": metrics,
            "executive_summary": summary,
            "incident_count": len(incidents),
        }
        logger.info(f"[Reporter] Dashboard metrics generated. {len(incidents)} incidents summarised.")
        return result

    def chat(self, question: str, context: Optional[str] = None) -> str:
        return (
            f"As the Reporter agent, I track all metrics and generate reports. "
            f"Your question: '{question}'. "
            f"Check the Reports page for downloadable summaries, or the Home Dashboard for live stats. "
            f"Context: {context or 'No active report context.'}"
        )
